In [17]:
from google.colab import drive
drive.mount('drive')

Drive already mounted at drive; to attempt to forcibly remount, call drive.mount("drive", force_remount=True).


In [18]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/CL/Day_5_6/diamonds_preprocessed.csv')
df

carat  cut  color  clarity  depth  table  price     x     y     z
0       0.23    2      1        3   61.5   55.0    326  3.95  3.98  2.43
1       0.21    3      1        2   59.8   61.0    326  3.89  3.84  2.31
2       0.23    1      1        4   56.9   65.0    327  4.05  4.07  2.31
3       0.29    3      5        5   62.4   58.0    334  4.20  4.23  2.63
4       0.31    1      6        3   63.3   58.0    335  4.34  4.35  2.75
...      ...  ...    ...      ...    ...    ...    ...   ...   ...   ...
53894   0.72    2      0        2   60.8   57.0   2757  5.75  5.76  3.50
53895   0.72    1      0        2   63.1   55.0   2757  5.69  5.75  3.61
53896   0.70    4      0        2   62.8   60.0   2757  5.66  5.68  3.56
53897   0.86    3      4        3   61.0   58.0   2757  6.15  6.12  3.74
53898   0.75    2      0        3   62.2   55.0   2757  5.83  5.87  3.64

[53899 rows x 10 columns]

In [29]:
X = df.drop(['price'],axis=1)
y = df['price']
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X = df.drop(['price'],axis=1)
y = df['price']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

lreg = LinearRegression()
lreg.fit(X_train,y_train)
y_pred = lreg.predict(X_test)
from sklearn.metrics import r2_score

print(r2_score(y_test,y_pred))

0.8892348217787043


In [20]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [21]:
for i in range(len(df.columns) -1):
  pca = PCA(n_components=i,random_state=42)
  pca.fit_transform(X)
  print(pca.explained_variance_ratio_)


[]
[0.32966895]
[0.32966895 0.22862533]
[0.32966895 0.22862533 0.1677514 ]
[0.32966895 0.22862533 0.1677514  0.11577729]
[0.32966895 0.22862533 0.1677514  0.11577729 0.10047729]
[0.32966895 0.22862533 0.1677514  0.11577729 0.10047729 0.05708701]
[0.32966895 0.22862533 0.1677514  0.11577729 0.10047729 0.05708701
 0.00049465]
[3.29668951e-01 2.28625328e-01 1.67751400e-01 1.15777291e-01
 1.00477285e-01 5.70870058e-02 4.94654974e-04 9.33535296e-05]


In [31]:
pca = PCA(n_components=0.80,random_state=42)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_reduced = pca.fit_transform(X_scaled)
print(pca.explained_variance_ratio_)
print(pca.explained_variance_ratio_.sum())
diamonds_pca_df = pd.DataFrame(X_reduced,columns=['PC1','PC2','PC3','PC4'])
diamonds_pca_df['price'] = y

[0.4627337  0.15989306 0.11000858 0.09603546]
0.8286708008894065


In [32]:
diamonds_pca_df

PC1       PC2       PC3       PC4  price
0     -3.121200  0.566012  0.900603 -0.000728    326
1     -2.905886 -2.203372  1.645301  0.650719    326
2     -2.706652 -3.656157  1.484084 -0.810089    327
3     -2.288152 -0.064449 -1.227357  1.437467    334
4     -1.831926  1.430059 -0.169909  1.948910    335
...         ...       ...       ...       ...    ...
53894 -0.232855 -0.161859  1.726819 -0.774303   2757
53895 -0.298767  1.886821  1.809102 -0.907386   2757
53896 -0.092514 -0.962797  1.576485  0.108204   2757
53897  0.797056 -0.562437 -0.142977  0.812355   2757
53898 -0.204560  0.974794  1.106270 -1.057291   2757

[53899 rows x 5 columns]

In [33]:
from sklearn.linear_model import LinearRegression

from sklearn.model_selection import train_test_split

X = diamonds_pca_df.drop(['price'],axis=1)
y = diamonds_pca_df['price']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

lreg = LinearRegression()
lreg.fit(X_train,y_train)
y_pred = lreg.predict(X_test)
from sklearn.metrics import r2_score

print(r2_score(y_test,y_pred))

0.8280632552968803
